input { 
  beats {
    port => 5044
  }
}

output {
        if [beat][hostname] == "usa0300lv1097" or [beat][hostname] == "usa0300lv1098" {
                elasticsearch {
                        hosts => "localhost:9200"
                        manage_template => false
                        index => "test-tomcat-%{+YYYY.MM.dd}"
                        document_type => "%{[@metadata][type]}"
                }
        }
        else if [beat][hostname] == "usa0300lv1095" or [beat][hostname] == "usa0300lv1096" {
                elasticsearch {
                        hosts => "localhost:9200"
                        manage_template => false
                        index => "prod-tomcat-%{+YYYY.MM.dd}"
                        document_type => "%{[@metadata][type]}"
                }
        }
        else if [beat][hostname] == "usa7061lv1113" or [beat][hostname] == "usa7061lv956" {
                elasticsearch {
                        hosts => "localhost:9200"
                        manage_template => false
                        index => "da-tomcat-%{+YYYY.MM.dd}"
                        document_type => "%{[@metadata][type]}"
                }
        }
        else {
                elasticsearch {
                        hosts => "localhost:9200"
                        manage_template => false
                        index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
                        document_type => "%{[@metadata][type]}"
                }
        }
}
